import 'package:flutter/material.dart';

class AppConfigs {
  static const baseUrl = 'https://api.dofhunt.200lab.io';
  static const userToken =
      "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOltdLCJlbWFpbCI6InBodWNuZ3V5ZW4uaW8ub3V0bG9va0BnbWFpbC5jb20iLCJleHAiOjE2ODM2NDQyMDMsImlhdCI6MTY4MTA1MjIwMywiaXNzIjoiIiwianRpIjoiNDQ4MmMzNDAtZDZjNi00NjQ3LTg0MWMtOGEyNGIyMDNlOTcwIiwibmJmIjoxNjgxMDUyMjAzLCJzY3AiOlsib2ZmbGluZSJdLCJzdWIiOiI3MjQ3IiwidXNlcl9pZCI6IjcyNDcifQ.G824pFJ6SmrOLtxuEbAVyz0OiG6jT6IjMHHi79PjzjHmtapFG1RzanwLPRq9v2res6EN-CaXPqDXvsqXPptxPncZE9zcJuBwA4eqWLPgSTsj3CTFKe1eV6x57BH9qVwEE3r-ucAfZQAJxAe3mkfvn6hL3_P6bu1Kh-eTpY-RJJM";
}
